// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package batchsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	FetchBatchRowsData(ctx context.Context, batch pgtype.UUID) ([]FetchBatchRowsDataRow, error)
	GetBatchStatus(ctx context.Context, id pgtype.UUID) (StatusEnum, error)
	InsertIntoBatchRows(ctx context.Context, arg InsertIntoBatchRowsParams) error
	InsertIntoBatches(ctx context.Context, arg InsertIntoBatchesParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
