package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"strconv"
	"strings"

	"github.com/dave/jennifer/jen"
)

// emitBuildFile renders the generated App type and Build function.
//
// Jennifer handles Go layout, block structure, and import rendering. The
// generator still keeps source fragments as strings because load.go already
// validated them and preserved the user's package aliases. We parse the stored
// fragments again only at the edge where the emitter needs a Go code object.
func emitBuildFile(model graphModel, resolved resolvedGraph, imports []importRef) ([]byte, error) {
	file := jen.NewFile(model.packageName)
	file.HeaderComment("Code generated by alya-di. DO NOT EDIT.")
	addImports(file, imports)
	importPaths := importPathByAlias(imports)

	if err := emitAppType(file, resolved, importPaths); err != nil {
		return nil, err
	}
	file.Line()
	if err := emitBuildFunc(file, model, resolved, imports, importPaths); err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := file.Render(&buf); err != nil {
		return nil, fmt.Errorf("format generated code: %w", err)
	}
	return buf.Bytes(), nil
}

// addImports registers the imports referenced by the generated file.
//
// The loader records the package aliases used in the source graph declaration.
// Reusing those names keeps the generated file readable and avoids a separate
// import-name inference step in the emitter.
func addImports(file *jen.File, imports []importRef) {
	for _, ref := range imports {
		switch ref.Alias {
		case ".", "_":
			file.ImportAlias(ref.Path, ref.Alias)
		default:
			file.ImportName(ref.Path, ref.Alias)
		}
	}
}

// importPathByAlias indexes imports by the local name used in the source file.
//
// The code renderer uses this map to turn selector expressions into package
// imports when the selector refers to an imported package.
func importPathByAlias(imports []importRef) map[string]string {
	result := make(map[string]string, len(imports))
	for _, ref := range imports {
		result[ref.Alias] = ref.Path
	}
	return result
}

// emitAppType writes the output struct requested by di.Outputs(...).
//
// The fields are emitted in the same order as the graph declaration so the
// generated type stays predictable when a service adds or reorders outputs.
func emitAppType(file *jen.File, resolved resolvedGraph, importPaths map[string]string) error {
	file.Comment("App contains the graph outputs requested by di.Outputs(...).")
	fields := make([]jen.Code, 0, len(resolved.outputs))
	for _, output := range resolved.outputs {
		typeCode, err := codeForTypeExpr(output.requested.exprString, importPaths)
		if err != nil {
			return fmt.Errorf("render output %s: %w", output.requested.exprString, err)
		}
		fields = append(fields, jen.Id(output.fieldName).Add(typeCode))
	}
	file.Type().Id("App").Struct(fields...)
	return nil
}

// emitBuildFunc writes the generated Build function body.
//
// The build plan is already topologically sorted by resolve.go, so the emitter
// can render providers in order without performing graph logic again. Cleanup is
// handled with a stack because the last provider to start should be the first
// one to shut down.
func emitBuildFunc(file *jen.File, model graphModel, resolved resolvedGraph, imports []importRef, importPaths map[string]string) error {
	reservedNames := makeReservedNames(imports)
	inputVarNames := buildInputVarNames(model.inputs, reservedNames)
	providerVarNames := buildProviderVarNames(resolved.providerOrder, reservedNames, inputVarNames)

	params := make([]jen.Code, 0, len(model.inputs))
	for _, input := range model.inputs {
		typeCode, err := codeForTypeExpr(input.exprString, importPaths)
		if err != nil {
			return fmt.Errorf("render input %s: %w", input.exprString, err)
		}
		params = append(params, jen.Id(inputVarNames[input.typeKey]).Add(typeCode))
	}

	providerSteps := make([][]jen.Code, 0, len(resolved.providerOrder))
	for _, node := range resolved.providerOrder {
		steps, err := providerStepCodes(node, inputVarNames, providerVarNames, importPaths)
		if err != nil {
			return err
		}
		providerSteps = append(providerSteps, steps)
	}

	invokeSteps := make([][]jen.Code, 0, len(resolved.invokes))
	for _, invoke := range resolved.invokes {
		steps, err := invokeStepCodes(invoke, inputVarNames, providerVarNames, importPaths)
		if err != nil {
			return err
		}
		invokeSteps = append(invokeSteps, steps)
	}

	file.Comment("Build constructs the dependency graph declared by Graph.")
	file.Func().Id("Build").Params(params...).Params(
		jen.Op("*").Id("App"),
		jen.Func().Params(),
		jen.Error(),
	).BlockFunc(func(g *jen.Group) {
		g.Id("cleanups").Op(":=").Make(jen.Index().Add(jen.Func().Params()), jen.Lit(0))
		g.Line()
		g.Id("runCleanups").Op(":=").Func().Params().BlockFunc(func(cleanup *jen.Group) {
			cleanup.For(
				jen.Id("i").Op(":=").Len(jen.Id("cleanups")).Op("-").Lit(1),
				jen.Id("i").Op(">=").Lit(0),
				jen.Id("i").Op("--"),
			).BlockFunc(func(loop *jen.Group) {
				loop.If(jen.Id("cleanups").Index(jen.Id("i")).Op("!=").Nil()).Block(
					jen.Id("cleanups").Index(jen.Id("i")).Call(),
				)
			})
		})
		g.Line()

		for _, steps := range providerSteps {
			for _, step := range steps {
				g.Add(step)
			}
			g.Line()
		}

		for _, steps := range invokeSteps {
			for _, step := range steps {
				g.Add(step)
			}
			g.Line()
		}

		g.Id("app").Op(":=").Op("&").Id("App").Values()
		for _, output := range resolved.outputs {
			g.Id("app").Dot(output.fieldName).Op("=").Add(jen.Id(referenceName(output.source, inputVarNames, providerVarNames)))
		}
		g.Line()
		g.Return(jen.Id("app"), jen.Id("runCleanups"), jen.Nil())
	})
	return nil
}

// providerStepCodes writes one provider call and its cleanup/error handling.
//
// Providers are emitted after resolution has confirmed that every dependency is
// available. The emitter only needs to preserve the result order and the cleanup
// stack discipline.
func providerStepCodes(node *providerNode, inputVarNames, providerVarNames map[string]string, importPaths map[string]string) ([]jen.Code, error) {
	varName := providerVarNames[node.ref.result.typeKey]
	cleanupVar := makeCleanupName(node.ref.result.typeValue, varName)
	call, err := callExpr(node.ref.exprString, importPaths)
	if err != nil {
		return nil, fmt.Errorf("render provider %s: %w", node.ref.exprString, err)
	}
	args := dependencyArgs(node.dependencies, inputVarNames, providerVarNames)
	callSite := call.Call(argCodes(args)...)

	switch {
	case node.ref.hasCleanup:
		return []jen.Code{
			jen.List(jen.Id(varName), jen.Id(cleanupVar), jen.Id("err")).Op(":=").Add(callSite),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(
				jen.Id("runCleanups").Call(),
				jen.Return(jen.Nil(), jen.Nil(), jen.Id("err")),
			),
			jen.If(jen.Id(cleanupVar).Op("!=").Nil()).Block(
				jen.Id("cleanups").Op("=").Append(jen.Id("cleanups"), jen.Id(cleanupVar)),
			),
		}, nil
	case node.ref.hasError:
		return []jen.Code{
			jen.List(jen.Id(varName), jen.Id("err")).Op(":=").Add(callSite),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(
				jen.Id("runCleanups").Call(),
				jen.Return(jen.Nil(), jen.Nil(), jen.Id("err")),
			),
		}, nil
	default:
		return []jen.Code{jen.Id(varName).Op(":=").Add(callSite)}, nil
	}
}

// invokeStepCodes writes one invoke call.
//
// Invokes are side-effect hooks such as route registration. They run after all
// providers have succeeded, and any returned error unwinds the cleanup stack.
func invokeStepCodes(invoke resolvedInvoke, inputVarNames, providerVarNames map[string]string, importPaths map[string]string) ([]jen.Code, error) {
	call, err := callExpr(invoke.ref.exprString, importPaths)
	if err != nil {
		return nil, fmt.Errorf("render invoke %s: %w", invoke.ref.exprString, err)
	}
	args := dependencyArgs(invoke.dependencies, inputVarNames, providerVarNames)
	callSite := call.Call(argCodes(args)...)

	if invoke.ref.returnsErr {
		return []jen.Code{
			jen.Id("err").Op(":=").Add(callSite),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(
				jen.Id("runCleanups").Call(),
				jen.Return(jen.Nil(), jen.Nil(), jen.Id("err")),
			),
		}, nil
	}

	return []jen.Code{callSite}, nil
}

// argCodes converts a comma-separated argument list into jennifer codes.
//
// The arguments are always local identifiers produced by the resolver, so they
// can be rendered directly without another parser pass.
func argCodes(args string) []jen.Code {
	if args == "" {
		return nil
	}
	parts := strings.Split(args, ", ")
	codes := make([]jen.Code, 0, len(parts))
	for _, part := range parts {
		codes = append(codes, jen.Id(part))
	}
	return codes
}

// callExpr parses a function expression from the graph and returns a jennifer
// statement that can be turned into a call.
//
// Alya keeps function expressions intentionally narrow. Providers and invokes
// are expected to be ordinary function names or package-qualified function
// names. If the graph stores anything more complex, the generator returns an
// error instead of guessing.
func callExpr(expr string, importPaths map[string]string) (*jen.Statement, error) {
	code, err := codeForParsedExpr(expr, importPaths)
	if err != nil {
		return nil, err
	}
	return code, nil
}

// codeForTypeExpr renders one type expression used by Inputs, Outputs, and
// provider results.
func codeForTypeExpr(expr string, importPaths map[string]string) (*jen.Statement, error) {
	return codeForParsedExpr(expr, importPaths)
}

// codeForParsedExpr converts a parsed Go expression into a jennifer statement.
//
// The generator only needs a small expression subset: names, package-qualified
// names, pointers, slices, arrays, maps, function types, and generic type
// arguments. Those cover the normal constructor and graph signatures used by
// Alya services.
func codeForParsedExpr(expr string, importPaths map[string]string) (*jen.Statement, error) {
	parsed, err := parser.ParseExpr(expr)
	if err != nil {
		return nil, fmt.Errorf("parse expression %q: %w", expr, err)
	}
	stmt, err := codeForAST(parsed, importPaths)
	if err != nil {
		return nil, fmt.Errorf("render expression %q: %w", expr, err)
	}
	return stmt, nil
}

func codeForAST(expr ast.Expr, importPaths map[string]string) (*jen.Statement, error) {
	switch e := expr.(type) {
	case *ast.Ident:
		return jen.Id(e.Name), nil
	case *ast.SelectorExpr:
		if ident, ok := e.X.(*ast.Ident); ok {
			if path, ok := importPaths[ident.Name]; ok {
				return jen.Qual(path, e.Sel.Name), nil
			}
		}
		base, err := codeForAST(e.X, importPaths)
		if err != nil {
			return nil, err
		}
		return base.Dot(e.Sel.Name), nil
	case *ast.StarExpr:
		inner, err := codeForAST(e.X, importPaths)
		if err != nil {
			return nil, err
		}
		return jen.Op("*").Add(inner), nil
	case *ast.ArrayType:
		inner, err := codeForAST(e.Elt, importPaths)
		if err != nil {
			return nil, err
		}
		if e.Len == nil {
			return jen.Index().Add(inner), nil
		}
		length, err := codeForAST(e.Len, importPaths)
		if err != nil {
			return nil, err
		}
		return jen.Index(length).Add(inner), nil
	case *ast.MapType:
		key, err := codeForAST(e.Key, importPaths)
		if err != nil {
			return nil, err
		}
		value, err := codeForAST(e.Value, importPaths)
		if err != nil {
			return nil, err
		}
		return jen.Map(key).Add(value), nil
	case *ast.FuncType:
		return codeForFuncType(e, importPaths)
	case *ast.IndexExpr:
		base, err := codeForAST(e.X, importPaths)
		if err != nil {
			return nil, err
		}
		index, err := codeForAST(e.Index, importPaths)
		if err != nil {
			return nil, err
		}
		return base.Index(index), nil
	case *ast.IndexListExpr:
		base, err := codeForAST(e.X, importPaths)
		if err != nil {
			return nil, err
		}
		indices := make([]jen.Code, 0, len(e.Indices))
		for _, index := range e.Indices {
			code, err := codeForAST(index, importPaths)
			if err != nil {
				return nil, err
			}
			indices = append(indices, code)
		}
		return base.Index(indices...), nil
	case *ast.ParenExpr:
		return codeForAST(e.X, importPaths)
	case *ast.UnaryExpr:
		inner, err := codeForAST(e.X, importPaths)
		if err != nil {
			return nil, err
		}
		return jen.Op(e.Op.String()).Add(inner), nil
	case *ast.BinaryExpr:
		left, err := codeForAST(e.X, importPaths)
		if err != nil {
			return nil, err
		}
		right, err := codeForAST(e.Y, importPaths)
		if err != nil {
			return nil, err
		}
		return left.Op(e.Op.String()).Add(right), nil
	case *ast.CallExpr:
		base, err := codeForAST(e.Fun, importPaths)
		if err != nil {
			return nil, err
		}
		args := make([]jen.Code, 0, len(e.Args))
		for _, arg := range e.Args {
			code, err := codeForAST(arg, importPaths)
			if err != nil {
				return nil, err
			}
			args = append(args, code)
		}
		return base.Call(args...), nil
	case *ast.BasicLit:
		return basicLitCode(e)
	default:
		return nil, fmt.Errorf("unsupported expression type %T", expr)
	}
}

func codeForFuncType(ft *ast.FuncType, importPaths map[string]string) (*jen.Statement, error) {
	stmt := jen.Func()
	if ft.Params == nil || len(ft.Params.List) == 0 {
		stmt = stmt.Params()
	} else {
		params := make([]jen.Code, 0, len(ft.Params.List))
		for _, field := range ft.Params.List {
			code, err := codeForAST(field.Type, importPaths)
			if err != nil {
				return nil, err
			}
			params = append(params, code)
		}
		stmt = stmt.Params(params...)
	}
	if ft.Results != nil && len(ft.Results.List) > 0 {
		results := make([]jen.Code, 0, len(ft.Results.List))
		for _, field := range ft.Results.List {
			code, err := codeForAST(field.Type, importPaths)
			if err != nil {
				return nil, err
			}
			results = append(results, code)
		}
		stmt = stmt.Params(results...)
	}
	return stmt, nil
}

func basicLitCode(lit *ast.BasicLit) (*jen.Statement, error) {
	switch lit.Kind {
	case token.INT:
		v, err := strconv.ParseInt(lit.Value, 0, 64)
		if err != nil {
			return nil, fmt.Errorf("parse int literal %q: %w", lit.Value, err)
		}
		return jen.Lit(int(v)), nil
	case token.FLOAT:
		v, err := strconv.ParseFloat(lit.Value, 64)
		if err != nil {
			return nil, fmt.Errorf("parse float literal %q: %w", lit.Value, err)
		}
		return jen.Lit(v), nil
	case token.STRING:
		v, err := strconv.Unquote(lit.Value)
		if err != nil {
			return nil, fmt.Errorf("parse string literal %q: %w", lit.Value, err)
		}
		return jen.Lit(v), nil
	case token.CHAR:
		v, err := strconv.Unquote(lit.Value)
		if err != nil {
			return nil, fmt.Errorf("parse rune literal %q: %w", lit.Value, err)
		}
		runes := []rune(v)
		if len(runes) != 1 {
			return nil, fmt.Errorf("expected one rune in literal %q", lit.Value)
		}
		return jen.LitRune(runes[0]), nil
	default:
		return nil, fmt.Errorf("unsupported literal kind %s", lit.Kind)
	}
}

// buildInputVarNames derives stable local names for Build parameters.
func buildInputVarNames(inputs []typeRef, reserved map[string]bool) map[string]string {
	used := cloneNameSet(reserved)
	result := make(map[string]string, len(inputs))
	for _, input := range inputs {
		result[input.typeKey] = uniqueLocalName(makeParamName(input.typeValue), used)
	}
	return result
}

// buildProviderVarNames derives stable local names for provider results.
func buildProviderVarNames(nodes []*providerNode, reserved map[string]bool, inputs map[string]string) map[string]string {
	used := cloneNameSet(reserved)
	for _, name := range inputs {
		used[name] = true
	}
	result := make(map[string]string, len(nodes))
	for _, node := range nodes {
		result[node.ref.result.typeKey] = uniqueLocalName(makeVariableName(node.ref.result.typeValue), used)
	}
	return result
}

// makeReservedNames collects identifiers that should not be reused for generated
// local variables, such as import aliases and helper names already used in the
// emitted Build function.
func makeReservedNames(imports []importRef) map[string]bool {
	reserved := map[string]bool{
		"app":         true,
		"cleanups":    true,
		"err":         true,
		"runCleanups": true,
	}
	for _, ref := range imports {
		reserved[ref.Alias] = true
	}
	return reserved
}

func cloneNameSet(source map[string]bool) map[string]bool {
	cloned := make(map[string]bool, len(source))
	for key, value := range source {
		cloned[key] = value
	}
	return cloned
}

func uniqueLocalName(base string, used map[string]bool) string {
	candidate := base
	if candidate == "" {
		candidate = "value"
	}
	if !used[candidate] {
		used[candidate] = true
		return candidate
	}
	candidate = candidate + "Value"
	if !used[candidate] {
		used[candidate] = true
		return candidate
	}
	for i := 2; ; i++ {
		next := fmt.Sprintf("%s%d", candidate, i)
		if !used[next] {
			used[next] = true
			return next
		}
	}
}

// dependencyArgs converts resolved dependencies into the argument list passed to
// one provider or invoke function.
func dependencyArgs(deps []dependencyRef, inputVarNames, providerVarNames map[string]string) string {
	args := make([]string, 0, len(deps))
	for _, dep := range deps {
		args = append(args, referenceName(dep.source, inputVarNames, providerVarNames))
	}
	return strings.Join(args, ", ")
}

// referenceName returns the local identifier used for one resolved source.
func referenceName(source typeRef, inputVarNames, providerVarNames map[string]string) string {
	if name, ok := inputVarNames[source.typeKey]; ok {
		return name
	}
	return providerVarNames[source.typeKey]
}

// makeParamName derives a readable parameter name from a type.
func makeParamName(t types.Type) string {
	name := lowerCamel(baseTypeName(t))
	switch name {
	case "config", "appConfig":
		return "cfg"
	case "engine":
		return "engine"
	case "service":
		return "svc"
	case "validator":
		return "validator"
	case "logger":
		return "logger"
	case "provider":
		return "provider"
	case "repository":
		return "repo"
	case "db":
		return "db"
	default:
		if name == "" {
			return "value"
		}
		return name
	}
}

// makeVariableName derives a stable local variable name from a concrete type.
func makeVariableName(t types.Type) string {
	name := lowerCamel(baseTypeName(t))
	if name == "" {
		return "value"
	}
	return name
}

// makeCleanupName derives a cleanup variable name associated with a provider.
func makeCleanupName(t types.Type, varName string) string {
	base := baseTypeName(t)
	if base == "" {
		base = upperFirst(varName)
	}
	return "cleanup" + base
}

// baseTypeName extracts a readable identifier from a type. Named pointer types
// use the element name. Interfaces and unnamed types fall back to an empty
// string.
func baseTypeName(t types.Type) string {
	switch typed := t.(type) {
	case *types.Named:
		return typed.Obj().Name()
	case *types.Pointer:
		return baseTypeName(typed.Elem())
	}
	return ""
}

// lowerCamel converts a type name into a lower-camel local identifier while
// keeping common initialisms readable. For example, SQLCRepository becomes
// sqlcRepository instead of sQLCRepository.
func lowerCamel(name string) string {
	if name == "" {
		return ""
	}
	runes := []rune(name)
	cut := 1
	for cut < len(runes) {
		if !isUpper(runes[cut]) {
			break
		}
		if cut+1 < len(runes) && !isUpper(runes[cut+1]) {
			break
		}
		cut++
	}
	return strings.ToLower(string(runes[:cut])) + string(runes[cut:])
}

func isUpper(r rune) bool {
	return r >= 'A' && r <= 'Z'
}

func upperFirst(value string) string {
	if value == "" {
		return ""
	}
	runes := []rune(value)
	if runes[0] >= 'a' && runes[0] <= 'z' {
		runes[0] = runes[0] - ('a' - 'A')
	}
	return string(runes)
}
