package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"path/filepath"
	"strings"
)

// emitBuildFile renders the generated App struct and Build function.
func emitBuildFile(model graphModel, resolved resolvedGraph, imports []importRef) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintln(&buf, "// Code generated by alya-di. DO NOT EDIT.")
	fmt.Fprintf(&buf, "package %s\n\n", model.packageName)

	if len(imports) > 0 {
		fmt.Fprintln(&buf, "import (")
		for _, ref := range imports {
			if ref.Alias == filepath.Base(ref.Path) {
				fmt.Fprintf(&buf, "\t%q\n", ref.Path)
				continue
			}
			fmt.Fprintf(&buf, "\t%s %q\n", ref.Alias, ref.Path)
		}
		fmt.Fprintln(&buf, ")")
		fmt.Fprintln(&buf)
	}

	fmt.Fprintln(&buf, "// App contains the graph outputs requested by di.Outputs(...).")
	fmt.Fprintln(&buf, "type App struct {")
	for _, output := range resolved.outputs {
		fmt.Fprintf(&buf, "\t%s %s\n", output.fieldName, output.requested.exprString)
	}
	fmt.Fprintln(&buf, "}")
	fmt.Fprintln(&buf)

	reservedNames := makeReservedNames(imports)
	inputVarNames := buildInputVarNames(model.inputs, reservedNames)
	providerVarNames := buildProviderVarNames(resolved.providerOrder, reservedNames, inputVarNames)

	fmt.Fprintln(&buf, "// Build constructs the dependency graph declared by Graph.")
	fmt.Fprintf(&buf, "func Build(%s) (*App, func(), error) {\n", buildParamList(model.inputs, inputVarNames))
	fmt.Fprintln(&buf, "\tcleanups := make([]func(), 0)")
	fmt.Fprintln(&buf, "\trunCleanups := func() {")
	fmt.Fprintln(&buf, "\t\tfor i := len(cleanups) - 1; i >= 0; i-- {")
	fmt.Fprintln(&buf, "\t\t\tif cleanups[i] != nil {")
	fmt.Fprintln(&buf, "\t\t\t\tcleanups[i]()")
	fmt.Fprintln(&buf, "\t\t\t}")
	fmt.Fprintln(&buf, "\t\t}")
	fmt.Fprintln(&buf, "\t}")
	fmt.Fprintln(&buf)

	for _, node := range resolved.providerOrder {
		varName := providerVarNames[node.ref.result.typeKey]
		cleanupVar := makeCleanupName(node.ref.result.typeValue, varName)
		args := dependencyArgs(node.dependencies, inputVarNames, providerVarNames)
		switch {
		case node.ref.hasCleanup:
			fmt.Fprintf(&buf, "\t%s, %s, err := %s(%s)\n", varName, cleanupVar, node.ref.exprString, args)
			fmt.Fprintln(&buf, "\tif err != nil {")
			fmt.Fprintln(&buf, "\t\trunCleanups()")
			fmt.Fprintln(&buf, "\t\treturn nil, nil, err")
			fmt.Fprintln(&buf, "\t}")
			fmt.Fprintf(&buf, "\tif %s != nil {\n", cleanupVar)
			fmt.Fprintf(&buf, "\t\tcleanups = append(cleanups, %s)\n", cleanupVar)
			fmt.Fprintln(&buf, "\t}")
		case node.ref.hasError:
			fmt.Fprintf(&buf, "\t%s, err := %s(%s)\n", varName, node.ref.exprString, args)
			fmt.Fprintln(&buf, "\tif err != nil {")
			fmt.Fprintln(&buf, "\t\trunCleanups()")
			fmt.Fprintln(&buf, "\t\treturn nil, nil, err")
			fmt.Fprintln(&buf, "\t}")
		default:
			fmt.Fprintf(&buf, "\t%s := %s(%s)\n", varName, node.ref.exprString, args)
		}
		fmt.Fprintln(&buf)
	}

	for _, invoke := range resolved.invokes {
		args := dependencyArgs(invoke.dependencies, inputVarNames, providerVarNames)
		if invoke.ref.returnsErr {
			fmt.Fprintf(&buf, "\tif err := %s(%s); err != nil {\n", invoke.ref.exprString, args)
			fmt.Fprintln(&buf, "\t\trunCleanups()")
			fmt.Fprintln(&buf, "\t\treturn nil, nil, err")
			fmt.Fprintln(&buf, "\t}")
		} else {
			fmt.Fprintf(&buf, "\t%s(%s)\n", invoke.ref.exprString, args)
		}
		fmt.Fprintln(&buf)
	}

	fmt.Fprintln(&buf, "\tapp := &App{")
	for _, output := range resolved.outputs {
		fmt.Fprintf(&buf, "\t\t%s: %s,\n", output.fieldName, referenceName(output.source, inputVarNames, providerVarNames))
	}
	fmt.Fprintln(&buf, "\t}")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "\treturn app, runCleanups, nil")
	fmt.Fprintln(&buf, "}")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

// buildInputVarNames derives stable local names for Build parameters.
func buildInputVarNames(inputs []typeRef, reserved map[string]bool) map[string]string {
	used := cloneNameSet(reserved)
	result := make(map[string]string, len(inputs))
	for _, input := range inputs {
		result[input.typeKey] = uniqueLocalName(makeParamName(input.typeValue), used)
	}
	return result
}

// buildProviderVarNames derives stable local names for provider results.
func buildProviderVarNames(nodes []*providerNode, reserved map[string]bool, inputs map[string]string) map[string]string {
	used := cloneNameSet(reserved)
	for _, name := range inputs {
		used[name] = true
	}
	result := make(map[string]string, len(nodes))
	for _, node := range nodes {
		result[node.ref.result.typeKey] = uniqueLocalName(makeVariableName(node.ref.result.typeValue), used)
	}
	return result
}

// makeReservedNames collects identifiers that should not be reused for generated
// local variables, such as import aliases and helper names already used in the
// emitted Build function.
func makeReservedNames(imports []importRef) map[string]bool {
	reserved := map[string]bool{
		"app":         true,
		"cleanups":    true,
		"err":         true,
		"runCleanups": true,
	}
	for _, ref := range imports {
		reserved[ref.Alias] = true
	}
	return reserved
}

func cloneNameSet(source map[string]bool) map[string]bool {
	cloned := make(map[string]bool, len(source))
	for key, value := range source {
		cloned[key] = value
	}
	return cloned
}

func uniqueLocalName(base string, used map[string]bool) string {
	candidate := base
	if candidate == "" {
		candidate = "value"
	}
	if !used[candidate] {
		used[candidate] = true
		return candidate
	}
	candidate = candidate + "Value"
	if !used[candidate] {
		used[candidate] = true
		return candidate
	}
	for i := 2; ; i++ {
		next := fmt.Sprintf("%s%d", candidate, i)
		if !used[next] {
			used[next] = true
			return next
		}
	}
}

// buildParamList renders the generated Build function parameter list in the same
// order as di.Inputs(...).
func buildParamList(inputs []typeRef, inputVarNames map[string]string) string {
	parts := make([]string, 0, len(inputs))
	for _, input := range inputs {
		parts = append(parts, fmt.Sprintf("%s %s", inputVarNames[input.typeKey], input.exprString))
	}
	return strings.Join(parts, ", ")
}

// dependencyArgs converts resolved dependencies into the argument list passed to
// one provider or invoke function.
func dependencyArgs(deps []dependencyRef, inputVarNames, providerVarNames map[string]string) string {
	args := make([]string, 0, len(deps))
	for _, dep := range deps {
		args = append(args, referenceName(dep.source, inputVarNames, providerVarNames))
	}
	return strings.Join(args, ", ")
}

// referenceName returns the local identifier used for one resolved source.
func referenceName(source typeRef, inputVarNames, providerVarNames map[string]string) string {
	if name, ok := inputVarNames[source.typeKey]; ok {
		return name
	}
	return providerVarNames[source.typeKey]
}

// makeParamName derives a readable parameter name from a type.
func makeParamName(t types.Type) string {
	name := lowerCamel(baseTypeName(t))
	switch name {
	case "config", "appConfig":
		return "cfg"
	case "engine":
		return "engine"
	case "service":
		return "svc"
	case "validator":
		return "validator"
	case "logger":
		return "logger"
	case "provider":
		return "provider"
	case "repository":
		return "repo"
	case "db":
		return "db"
	default:
		if name == "" {
			return "value"
		}
		return name
	}
}

// makeVariableName derives a stable local variable name from a concrete type.
func makeVariableName(t types.Type) string {
	name := lowerCamel(baseTypeName(t))
	if name == "" {
		return "value"
	}
	return name
}

// makeCleanupName derives a cleanup variable name associated with a provider.
func makeCleanupName(t types.Type, varName string) string {
	base := baseTypeName(t)
	if base == "" {
		base = upperFirst(varName)
	}
	return "cleanup" + base
}

// baseTypeName extracts a readable identifier from a type. Named pointer types
// use the element name. Interfaces and unnamed types fall back to an empty
// string.
func baseTypeName(t types.Type) string {
	switch typed := t.(type) {
	case *types.Named:
		return typed.Obj().Name()
	case *types.Pointer:
		return baseTypeName(typed.Elem())
	}
	return ""
}

// lowerCamel converts a type name into a lower-camel local identifier while
// keeping common initialisms readable. For example, SQLCRepository becomes
// sqlcRepository instead of sQLCRepository.
func lowerCamel(name string) string {
	if name == "" {
		return ""
	}
	runes := []rune(name)
	cut := 1
	for cut < len(runes) {
		if !isUpper(runes[cut]) {
			break
		}
		if cut+1 < len(runes) && !isUpper(runes[cut+1]) {
			break
		}
		cut++
	}
	return strings.ToLower(string(runes[:cut])) + string(runes[cut:])
}

func isUpper(r rune) bool {
	return r >= 'A' && r <= 'Z'
}

func upperFirst(value string) string {
	if value == "" {
		return ""
	}
	runes := []rune(value)
	if runes[0] >= 'a' && runes[0] <= 'z' {
		runes[0] = runes[0] - ('a' - 'A')
	}
	return string(runes)
}
