package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestRunGenForRESTExample is a small end-to-end smoke test for the generator.
//
// It runs the generator against the REST SQLC example graph and checks for a few
// key markers in the emitted file. This keeps the test focused on the public
// workflow instead of internal helper details.
func TestRunGenForRESTExample(t *testing.T) {
	exampleDir := filepath.Join("..", "..", "examples", "rest-usersvc-sqlc-example")
	generatedPath := filepath.Join(exampleDir, "zz_generated_di_test.go")

	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("get working directory: %v", err)
	}
	defer func() {
		_ = os.Chdir(wd)
		_ = os.Remove(generatedPath)
	}()

	if err := os.Chdir(exampleDir); err != nil {
		t.Fatalf("chdir to example: %v", err)
	}
	if err := runGen([]string{"-graph", "Graph", "-out", "zz_generated_di_test.go"}); err != nil {
		t.Fatalf("run generator: %v", err)
	}

	content, err := os.ReadFile(generatedPath)
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	generated := string(content)
	checks := []string{
		"// Code generated by alya-di. DO NOT EDIT.",
		"func Build(engine *gin.Engine, cfg AppConfig) (*App, func(), error)",
		"transport.RegisterRoutes(serviceValue, userHandler, orderHandler)",
		"cleanupProvider",
	}
	for _, check := range checks {
		if !strings.Contains(generated, check) {
			t.Fatalf("generated file does not contain %q", check)
		}
	}
}
