ALTER TABLE users
ADD COLUMN username VARCHAR(255) NOT NULL,
ADD COLUMN phone_number VARCHAR(255),
ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

---- create above / drop below ----

ALTER TABLE users
DROP COLUMN IF EXISTS username,
DROP COLUMN IF EXISTS phone_number,
DROP COLUMN IF EXISTS created_at,
DROP COLUMN IF EXISTS updated_at;