// Code generated by alya-di. DO NOT EDIT.

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/remiges-tech/alya/examples/rest-usersvc-sqlc-example/app"
	"github.com/remiges-tech/alya/examples/rest-usersvc-sqlc-example/transport"
	"github.com/remiges-tech/alya/service"
)

// App contains the graph outputs requested by di.Outputs(...).
type App struct {
	Service      *service.Service
	UserHandler  *transport.UserHandler
	OrderHandler *transport.OrderHandler
}

// Build constructs the dependency graph declared by Graph.
func Build(engine *gin.Engine, cfg AppConfig) (*App, func(), error) {
	cleanups := make([]func(), 0)

	runCleanups := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			if cleanups[i] != nil {
				cleanups[i]()
			}
		}
	}

	serviceValue := service.NewService(engine)

	config := newPGConfig(cfg)

	provider, cleanupProvider, err := newPGProvider(config)
	if err != nil {
		runCleanups()
		return nil, nil, err
	}
	if cleanupProvider != nil {
		cleanups = append(cleanups, cleanupProvider)
	}

	sqlcRepository := newSQLCRepository(provider)

	userService := app.NewUserService(sqlcRepository)

	validator := newValidator()

	userHandler := transport.NewUserHandler(userService, validator)

	orderService := app.NewOrderService(sqlcRepository, sqlcRepository)

	orderHandler := transport.NewOrderHandler(orderService, validator)

	transport.RegisterRoutes(serviceValue, userHandler, orderHandler)

	app := &App{}
	app.Service = serviceValue
	app.UserHandler = userHandler
	app.OrderHandler = orderHandler

	return app, runCleanups, nil
}
