// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: batch.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const fetchBatchRowsData = `-- name: FetchBatchRowsData :many
SELECT rowid, line, input, status, reqat, doneat, res, blobrows, messages, doneby
FROM batchrows
WHERE batch = $1
`

type FetchBatchRowsDataRow struct {
	Rowid    int32                 `json:"rowid"`
	Line     int32                 `json:"line"`
	Input    json.RawMessage       `json:"input"`
	Status   StatusEnum            `json:"status"`
	Reqat    time.Time             `json:"reqat"`
	Doneat   sql.NullTime          `json:"doneat"`
	Res      pqtype.NullRawMessage `json:"res"`
	Blobrows pqtype.NullRawMessage `json:"blobrows"`
	Messages pqtype.NullRawMessage `json:"messages"`
	Doneby   sql.NullString        `json:"doneby"`
}

func (q *Queries) FetchBatchRowsData(ctx context.Context, batch uuid.UUID) ([]FetchBatchRowsDataRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchBatchRowsData, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchBatchRowsDataRow
	for rows.Next() {
		var i FetchBatchRowsDataRow
		if err := rows.Scan(
			&i.Rowid,
			&i.Line,
			&i.Input,
			&i.Status,
			&i.Reqat,
			&i.Doneat,
			&i.Res,
			&i.Blobrows,
			&i.Messages,
			&i.Doneby,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchStatus = `-- name: GetBatchStatus :one
SELECT status
FROM batches
WHERE id = $1
`

func (q *Queries) GetBatchStatus(ctx context.Context, id uuid.UUID) (StatusEnum, error) {
	row := q.db.QueryRowContext(ctx, getBatchStatus, id)
	var status StatusEnum
	err := row.Scan(&status)
	return status, err
}

const insertIntoBatchRows = `-- name: InsertIntoBatchRows :exec
INSERT INTO batchrows (batch, line, input, status, reqat)
VALUES ($1, $2, $3, 'queued', NOW())
`

type InsertIntoBatchRowsParams struct {
	Batch uuid.UUID       `json:"batch"`
	Line  int32           `json:"line"`
	Input json.RawMessage `json:"input"`
}

func (q *Queries) InsertIntoBatchRows(ctx context.Context, arg InsertIntoBatchRowsParams) error {
	_, err := q.db.ExecContext(ctx, insertIntoBatchRows, arg.Batch, arg.Line, arg.Input)
	return err
}

const insertIntoBatches = `-- name: InsertIntoBatches :one
INSERT INTO batches (id, app, op, context, status, reqat)
VALUES ($1, $2, $3, $4, 'queued', NOW())
RETURNING id
`

type InsertIntoBatchesParams struct {
	ID      uuid.UUID       `json:"id"`
	App     AppEnum         `json:"app"`
	Op      string          `json:"op"`
	Context json.RawMessage `json:"context"`
}

func (q *Queries) InsertIntoBatches(ctx context.Context, arg InsertIntoBatchesParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertIntoBatches,
		arg.ID,
		arg.App,
		arg.Op,
		arg.Context,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
