// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package querybuilder

import (
	"database/sql"
	"time"
)

type Voucher struct {
	ID              int64
	Date            time.Time
	DebitAccountID  sql.NullInt64
	CreditAccountID sql.NullInt64
	CostCentreID    sql.NullInt64
	Amount          sql.NullString
	Narration       sql.NullString
}
