// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Task struct {
	ID          int32                 `json:"id"`
	Type        string                `json:"type"`
	Status      string                `json:"status"`
	SubmittedAt time.Time             `json:"submitted_at"`
	StartedAt   sql.NullTime          `json:"started_at"`
	CompletedAt sql.NullTime          `json:"completed_at"`
	ResultPath  sql.NullString        `json:"result_path"`
	Details     pqtype.NullRawMessage `json:"details"`
}
