// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

type Config struct {
	ID          int32                 `json:"id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Active      sql.NullBool          `json:"active"`
	SchemaID    int32                 `json:"schema_id"`
	Values      json.RawMessage       `json:"values"`
	Tags        pqtype.NullRawMessage `json:"tags"`
	CreatedBy   string                `json:"created_by"`
	UpdatedBy   string                `json:"updated_by"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}

type Schema struct {
	ID          int32                 `json:"id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Fields      json.RawMessage       `json:"fields"`
	Tags        pqtype.NullRawMessage `json:"tags"`
	CreatedBy   string                `json:"created_by"`
	UpdatedBy   string                `json:"updated_by"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}
