// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Config struct {
	ID              int32                 `json:"id"`
	Name            string                `json:"name"`
	Active          sql.NullBool          `json:"active"`
	ActiveVersionID sql.NullInt32         `json:"active_version_id"`
	Description     sql.NullString        `json:"description"`
	Tags            pqtype.NullRawMessage `json:"tags"`
	CreatedBy       string                `json:"created_by"`
	UpdatedBy       string                `json:"updated_by"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
}

type ConfigVersion struct {
	ID              int32           `json:"id"`
	ConfigID        sql.NullInt32   `json:"config_id"`
	Version         string          `json:"version"`
	SchemaVersionID sql.NullInt32   `json:"schema_version_id"`
	Values          json.RawMessage `json:"values"`
	CreatedBy       sql.NullString  `json:"created_by"`
	UpdatedBy       sql.NullString  `json:"updated_by"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
}

type Employee struct {
	EmployeeID int32          `json:"employee_id" validate:"required"`
	Name       sql.NullString `json:"name"`
	Title      sql.NullString `json:"title"`
	Department sql.NullString `json:"department"`
}

type Schema struct {
	ID              int32                 `json:"id"`
	Name            string                `json:"name"`
	Active          sql.NullBool          `json:"active"`
	ActiveVersionID sql.NullInt32         `json:"active_version_id"`
	Description     sql.NullString        `json:"description"`
	Tags            pqtype.NullRawMessage `json:"tags"`
	CreatedBy       sql.NullString        `json:"created_by"`
	UpdatedBy       sql.NullString        `json:"updated_by"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
}

type SchemaVersion struct {
	ID        int32           `json:"id"`
	SchemaID  sql.NullInt32   `json:"schema_id"`
	Version   string          `json:"version"`
	Fields    json.RawMessage `json:"fields"`
	CreatedBy string          `json:"created_by"`
	UpdatedBy string          `json:"updated_by"`
	CreatedAt sql.NullTime    `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

type Voucher struct {
	VoucherID   int32          `json:"voucherId"`
	EmployeeID  int32          `json:"employee_id"`
	DateOfClaim time.Time      `json:"date_of_claim"`
	Amount      float64        `json:"amount"`
	Description sql.NullString `json:"description"`
}
